version: "3.9"
services:
  my-gotty:
    build: .
    hostname: mygotty
    ports:
      - "8989:8080"
    stdin_open: true
    tty: true
    privileged: true              # CRITICAL: Allows WARP to create network tunnels
    cap_add:
      - NET_ADMIN                 # CRITICAL: Gives permission to route proxy traffic
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0 
    volumes:
      - ./workspace:/workspace

# ----------------------------------------------------
# CRITICAL FIX: Lowering the MTU to prevent SSL drops
# ----------------------------------------------------
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1350
